import type { Config } from 'tailwindcss';

const config: Config = {
  content: ['./src/**/*.{js,ts,jsx,tsx,mdx}'],
  theme: {
    extend: {
      colors: {
        surface: '#f8f9ff',
        'surface-dim': '#ccdbf4',
        'surface-bright': '#f8f9ff',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#eff4ff',
        'surface-container': '#e6eeff',
        'surface-container-high': '#dde9ff',
        'surface-container-highest': '#d5e3fd',
        'surface-variant': '#d5e3fd',
        background: '#f8f9ff',
        primary: '#085693',
        'primary-container': '#06497D',
        'primary-fixed': '#d7e2ff',
        'primary-fixed-dim': '#abc7ff',
        secondary: '#00677d',
        'secondary-container': '#50d9fe',
        'secondary-fixed': '#b3ebff',
        'secondary-fixed-dim': '#4cd6fb',
        tertiary: '#323537',
        'tertiary-fixed': '#e0e3e5',
        'tertiary-fixed-dim': '#c4c7c9',
        error: '#ba1a1a',
        outline: '#737783',
        'outline-variant': '#c2c6d3',
        'surface-tint': '#085693',
        'inverse-primary': '#abc7ff',
        'inverse-surface': '#233144',
        'on-background': '#0d1c2f',
        'on-surface': '#0d1c2f',
        'on-surface-variant': '#424751',
        'on-primary': '#ffffff',
        'on-primary-container': '#9bbdff',
        'on-primary-fixed': '#001b3f',
        'on-primary-fixed-variant': '#00458f',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#005c70',
        'on-secondary-fixed': '#001f27',
        'on-secondary-fixed-variant': '#004e5f',
        'on-tertiary': '#ffffff',
        'on-tertiary-container': '#babcbe',
        'on-tertiary-fixed': '#191c1e',
        'on-tertiary-fixed-variant': '#444749',
        'inverse-on-surface': '#ebf1ff',
        'on-error': '#ffffff',
        'on-error-container': '#93000a',
      },
      spacing: {
        xs: '4px',
        base: '8px',
        sm: '12px',
        md: '24px',
        lg: '48px',
        xl: '80px',
        gutter: '24px',
        'container-max': '1280px',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        full: '9999px',
      },
      fontFamily: {
        sans: ['var(--font-inter)', 'sans-serif'],
        h1: ['var(--font-inter)', 'sans-serif'],
        h2: ['var(--font-inter)', 'sans-serif'],
        h3: ['var(--font-inter)', 'sans-serif'],
        'body-lg': ['var(--font-inter)', 'sans-serif'],
        'body-md': ['var(--font-inter)', 'sans-serif'],
        'body-sm': ['var(--font-inter)', 'sans-serif'],
        'label-caps': ['var(--font-inter)', 'sans-serif'],
        button: ['var(--font-inter)', 'sans-serif'],
      },
      fontSize: {
        h1: ['48px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '700' }],
        h2: ['36px', { lineHeight: '1.2', letterSpacing: '-0.01em', fontWeight: '600' }],
        h3: ['24px', { lineHeight: '1.3', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-sm': ['14px', { lineHeight: '1.5', fontWeight: '400' }],
        'label-caps': ['12px', { lineHeight: '1', letterSpacing: '0.05em', fontWeight: '600' }],
        button: ['16px', { lineHeight: '1', fontWeight: '600' }],
      },
      boxShadow: {
        ambient: '0 8px 32px rgba(8, 86, 147, 0.08)',
        lift: '0 12px 32px rgba(8, 86, 147, 0.16)',
        nav: '0 4px 14px rgba(8, 86, 147, 0.05)',
      },
      keyframes: {
        'card-bounce-up': {
          '0%': { transform: 'translateY(0)' },
          '35%': { transform: 'translateY(-12px)' },
          '60%': { transform: 'translateY(-8px)' },
          '80%': { transform: 'translateY(-10px)' },
          '100%': { transform: 'translateY(-9px)' },
        },
      },
      animation: {
        'card-bounce-up': 'card-bounce-up 520ms cubic-bezier(0.22, 1, 0.36, 1) forwards',
      },
      backgroundImage: {
        'brand-gradient': 'linear-gradient(135deg, #50d9fe 0%, #085693 100%)',
        'hero-overlay': 'linear-gradient(90deg, rgba(248,249,255,0.95) 0%, rgba(248,249,255,0.8) 45%, rgba(248,249,255,0) 100%)',
      },
      maxWidth: {
        'container-max': '1280px',
      },
    },
  },
  plugins: [],
};

export default config;
