import type { Config } from 'tailwindcss';

const cssColor = (variable: string) => `rgb(var(${variable}) / <alpha-value>)`;

const config: Config = {
  darkMode: ['class', '[data-theme="dark"]'],
  content: ['./src/**/*.{js,ts,jsx,tsx,mdx}'],
  theme: {
    extend: {
      colors: {
        surface: cssColor('--color-surface'),
        'surface-dim': cssColor('--color-surface-dim'),
        'surface-bright': cssColor('--color-surface-bright'),
        'surface-container-lowest': cssColor('--color-surface-container-lowest'),
        'surface-container-low': cssColor('--color-surface-container-low'),
        'surface-container': cssColor('--color-surface-container'),
        'surface-container-high': cssColor('--color-surface-container-high'),
        'surface-container-highest': cssColor('--color-surface-container-highest'),
        'surface-variant': cssColor('--color-surface-variant'),
        background: cssColor('--color-background'),
        primary: cssColor('--color-primary'),
        'primary-container': cssColor('--color-primary-container'),
        'primary-fixed': cssColor('--color-primary-fixed'),
        'primary-fixed-dim': cssColor('--color-primary-fixed-dim'),
        secondary: cssColor('--color-secondary'),
        'secondary-container': cssColor('--color-secondary-container'),
        'secondary-fixed': cssColor('--color-secondary-fixed'),
        'secondary-fixed-dim': cssColor('--color-secondary-fixed-dim'),
        tertiary: cssColor('--color-tertiary'),
        'tertiary-fixed': cssColor('--color-tertiary-fixed'),
        'tertiary-fixed-dim': cssColor('--color-tertiary-fixed-dim'),
        error: cssColor('--color-error'),
        outline: cssColor('--color-outline'),
        'outline-variant': cssColor('--color-outline-variant'),
        'surface-tint': cssColor('--color-surface-tint'),
        'inverse-primary': cssColor('--color-inverse-primary'),
        'inverse-surface': cssColor('--color-inverse-surface'),
        'on-background': cssColor('--color-on-background'),
        'on-surface': cssColor('--color-on-surface'),
        'on-surface-variant': cssColor('--color-on-surface-variant'),
        'on-primary': cssColor('--color-on-primary'),
        'on-primary-container': cssColor('--color-on-primary-container'),
        'on-primary-fixed': cssColor('--color-on-primary-fixed'),
        'on-primary-fixed-variant': cssColor('--color-on-primary-fixed-variant'),
        'on-secondary': cssColor('--color-on-secondary'),
        'on-secondary-container': cssColor('--color-on-secondary-container'),
        'on-secondary-fixed': cssColor('--color-on-secondary-fixed'),
        'on-secondary-fixed-variant': cssColor('--color-on-secondary-fixed-variant'),
        'on-tertiary': cssColor('--color-on-tertiary'),
        'on-tertiary-container': cssColor('--color-on-tertiary-container'),
        'on-tertiary-fixed': cssColor('--color-on-tertiary-fixed'),
        'on-tertiary-fixed-variant': cssColor('--color-on-tertiary-fixed-variant'),
        'inverse-on-surface': cssColor('--color-inverse-on-surface'),
        'on-error': cssColor('--color-on-error'),
        'on-error-container': cssColor('--color-on-error-container'),
      },
      spacing: {
        xs: '4px',
        base: '8px',
        sm: '12px',
        md: '24px',
        lg: '48px',
        xl: '80px',
        gutter: '24px',
        'container-max': '1280px',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        full: '9999px',
      },
      fontFamily: {
        sans: ['var(--font-inter)', 'sans-serif'],
        h1: ['var(--font-inter)', 'sans-serif'],
        h2: ['var(--font-inter)', 'sans-serif'],
        h3: ['var(--font-inter)', 'sans-serif'],
        'body-lg': ['var(--font-inter)', 'sans-serif'],
        'body-md': ['var(--font-inter)', 'sans-serif'],
        'body-sm': ['var(--font-inter)', 'sans-serif'],
        'label-caps': ['var(--font-inter)', 'sans-serif'],
        button: ['var(--font-inter)', 'sans-serif'],
      },
      fontSize: {
        h1: ['48px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '700' }],
        h2: ['36px', { lineHeight: '1.2', letterSpacing: '-0.01em', fontWeight: '600' }],
        h3: ['24px', { lineHeight: '1.3', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-sm': ['14px', { lineHeight: '1.5', fontWeight: '400' }],
        'label-caps': ['12px', { lineHeight: '1', letterSpacing: '0.05em', fontWeight: '600' }],
        button: ['16px', { lineHeight: '1', fontWeight: '600' }],
      },
      boxShadow: {
        ambient: 'var(--shadow-ambient)',
        lift: 'var(--shadow-lift)',
        nav: 'var(--shadow-nav)',
      },
      keyframes: {
        'card-bounce-up': {
          '0%': { transform: 'translateY(0)' },
          '35%': { transform: 'translateY(-12px)' },
          '60%': { transform: 'translateY(-8px)' },
          '80%': { transform: 'translateY(-10px)' },
          '100%': { transform: 'translateY(-9px)' },
        },
      },
      animation: {
        'card-bounce-up': 'card-bounce-up 520ms cubic-bezier(0.22, 1, 0.36, 1) forwards',
      },
      backgroundImage: {
        'brand-gradient': 'var(--brand-gradient)',
        'hero-overlay': 'var(--hero-overlay)',
        'card-gradient': 'var(--card-gradient)',
        'value-card-gradient': 'var(--value-card-gradient)',
        'notice-panel-gradient': 'var(--notice-panel-gradient)',
        'category-pill-gradient': 'var(--category-pill-gradient)',
      },
      maxWidth: {
        'container-max': '1280px',
      },
    },
  },
  plugins: [],
};

export default config;
